apiVersion: apps/v1
kind: Deployment
metadata:
  name: drum-machine-deployment
spec:
  selector:
    matchLabels:
      app: drum-machine
  replicas: 3
  template:
    metadata:
      labels:
        app: drum-machine
    spec:
      containers:
      - name: drum-machine
        image: efog/drum-machine-build-test:1
        ports:
        - containerPort: 80
